{
 "title": "Home",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "query": "SELECT SUM(\"last_cpus\") AS \"total_cpus\"\nFROM (\n  SELECT LAST(\"cpus\") AS \"last_cpus\"\n  FROM \"cpustat\"\n  WHERE \"host\" =~ /^pve-01$|^pve-02$|^pve-03$|^pve-03$|^pve-04$/\n  AND $timeFilter\n  GROUP BY \"host\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "pve-pds-pc" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"last\") \nFROM (\n  SELECT last(\"cpu\") AS \"last\" \n  FROM \"cpustat\" \n  WHERE (\"host\" = 'pve-01' OR \"host\" = 'pve-02' OR \"host\" = 'pve-04' OR \"host\" = 'pve-03')\n    AND time > now() - 1m\n  GROUP BY \"host\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT sum(\"last\") \nFROM (\n  SELECT last(\"memtotal\") AS \"last\" \n  FROM \"memory\" \n  WHERE (\"host\" = 'pve-01' OR \"host\" = 'pve-02' OR \"host\" = 'pve-04' OR \"host\" = 'pve-03')\n    AND $timeFilter\n  GROUP BY \"host\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "pve-01" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT (SUM(\"last_memused\") / SUM(\"last_memtotal\")) * 100 AS \"memory_usage_percentage\"\nFROM (\n  SELECT LAST(\"memused\") AS \"last_memused\", LAST(\"memtotal\") AS \"last_memtotal\"\n  FROM \"memory\"\n  WHERE \"host\" =~ /pve-01|pve-02|pve-04|pve-03/ AND time > now() - 1m\n  GROUP BY \"host\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "pve-01" }
     ]
    }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "CPU Count Breakdown",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host:",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"cpus\") AS \"cpus_count\", \"host\"\nFROM \"cpustat\"\nWHERE \"host\" =~ /^pve-01$|^pve-02$|^pve-03$|^pve-04$/\nAND $timeFilter\nGROUP BY \"host\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Break Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host:",
     "query": "SELECT \"memtotal\" AS \"Memory\"\nFROM \"memory\"\nWHERE \"host\" =~ /^pve-01$|^pve-02$|^pve-03$|^pve-04$/\nAND $timeFilter\nGROUP BY \"host\"\nfill(null)\n"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}