# Single-binary Loki, persisted locally

auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_concurrent_streams: 1000

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  metric_aggregation_enabled: true
  volume_enabled: true
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_cache_freshness_per_query: 10m
  allow_structured_metadata: true

pattern_ingester:
  enabled: true
  metric_aggregation:
    loki_address: loki:3100

ruler:
  storage:
    type: filesystem
    local:
      directory: /loki/rules
  alertmanager_url: http://alertmanager:9093

frontend:
  encoding: protobuf

# Disable anonymous usage reporting (optional)
analytics:
  reporting_enabled: false
