---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# dev-machine:
#   socket: /var/run/docker.sock

# docker-proxy:
#   host: homepage-dockerproxy
#   port: 2375
