networks:
  backend:
    external: true
  frontend:
    external: true

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc
    depends_on:
      # Launch fluentd after that elasticsearch is ready to connect
      elasticsearch:
        condition: service_healthy
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  fluentd-ui:
    build:
      context: build/fluentd-ui
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    networks:
      - frontend
      - backend

volumes:
  fluentd-buffer:
    driver: local
