networks:
  backend:
    external: true
  frontend:
    external: true

services:
  fluentd:
    build:
      context: build/fluentd
      dockerfile: Dockerfile
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - backend
    volumes:
      - ./conf:/fluentd/etc
      - fluentd-buffer:/fluentd/buffer
    environment:
      - FLUENT_UID=0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  fluentd-ui:
    build:
      context: build/fluentd-ui
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    networks:
      - frontend
      - backend

volumes:
  fluentd-buffer:
    driver: local
