global:
  scrape_interval: 15s # Reduced from 20s to 15s for more frequent scraping
  evaluation_interval: 15s # Reduced from 20s to 15s for more frequent evaluations
  scrape_timeout: 10s

remote_write:
  - url: "http://192.168.1.3:9090/api/v1/write"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: 
        - "192.168.1.3:9100"
        - "192.168.1.8:9100"
        - "192.168.1.10:9100"
        - "192.168.1.11:9100"
        - "192.168.1.12:9100"
  
  - job_name: "grafana-db-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.3:9104"]
  
  - job_name: 'ceph'
    static_configs:
      - targets: 
          - '192.168.1.8:9283'
          - '192.168.1.10:9283'
          - '192.168.1.11:9283'
          - '192.168.1.12:9283'


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/rules/*.yaml"
# Additional configurations can be added here as needed




