networks:
  backend:
    external: true
  frontend:
    external: true


services:
  sinlessgames:
    image: sinless777/sinlessgames-ui:1.0.89
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M