---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Monitoring:
    - Grafana:
        href: {{HOMEPAGE_VAR_GRAFANA_URL}}
        icon: grafana.svg
        siteMonitor: {{HOMEPAGE_VAR_GRAFANA_URL}}
        widget:
          type: grafana
          url: {{HOMEPAGE_VAR_GRAFANA_URL}}
          username: {{HOMEPAGE_VAR_GRAFANA_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - Prometheus:
        href: {{HOMEPAGE_VAR_SWARM_PROMETHEUS_URL}}
        icon: prometheus.svg
        siteMonitor: {{HOMEPAGE_VAR_SWARM_PROMETHEUS_URL}}
        widget:
          type: prometheus
          url: {{HOMEPAGE_VAR_SWARM_PROMETHEUS_URL}}
    - AlertManager:
        href: {{HOMEPAGE_VAR_ALERTMANAGER_URL}}
        icon: alertmanager.svg
        siteMonitor: {{HOMEPAGE_VAR_ALERTMANAGER_URL}}

- Infrastructure:
    - PVE-01:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        icon: proxmox.svg
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PVE_01_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_USER}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          node: pve-01
    - PVE-02:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        icon: proxmox.svg
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_USER}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          node: pve-02
    - PVE-03:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        icon: proxmox.svg
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_USER}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          node: pve-03
    - PVE-04:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        icon: proxmox.svg
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_USER}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          node: pve-04
    # - Gitlab:
    #     href: {{HOMEPAGE_VAR_GITLAB_URL}}
    #     icon: gitlab.svg
    #     siteMonitor: {{HOMEPAGE_VAR_GITLAB_URL}}
    #     widget:
    #         type: gitlab
    #         url: {{HOMEPAGE_VAR_GITLAB_URL}}
    #         key: {{HOMEPAGE_VAR_GITLAB_API_TOKEN}}
    #         user_id: {{HOMEPAGE_VAR_GITLAB_USER_ID}}

- Networking:
    - Unifi-Network-Controller:
        href: {{HOMEPAGE_VAR_UNIFI_URL}}
        description: ""
        icon: unifi.svg
        siteMonitor: {{HOMEPAGE_VAR_UNIFI_URL}}
        widget:
          type: unifi
          url: {{HOMEPAGE_VAR_UNIFI_URL}}
          username: {{HOMEPAGE_VAR_UNIFI_USER}}
          password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - PowerDNS:
        href: {{HOMEPAGE_VAR_POWERDNS_URL}}
        icon: powerdns.svg
        siteMonitor: {{HOMEPAGE_VAR_POWERDNS_URL}}
    - Netbox:
        href: {{HOMEPAGE_VAR_NETBOX_URL}}
        icon: netbox.svg
        siteMonitor: {{HOMEPAGE_VAR_NETBOX_URL}}
    - TailScale:
        href: https://login.tailscale.com/admin/machines
        icon: tailscale.svg
        siteMonitor: https://login.tailscale.com/admin/machines

- Cloudflare Tunnels:
    - Unifi-Controler-Tunnel:
        description: ""
        icon: cloudflare.svg
        widget:
            type: cloudflared
            accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}
            tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}
            key: {{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}

# - Automation:

# - Security:

- Databases:
    - InfluxDB:
        href: {{HOMEPAGE_VAR_INFLUXDB_URL}}
        icon: influxdb.svg
        siteMonitor: {{HOMEPAGE_VAR_INFLUXDB_URL}}
    - MinIO:
        href: {{HOMEPAGE_VAR_MINIO_URL}}
        icon: minio.svg
        siteMonitor: {{HOMEPAGE_VAR_MINIO_URL}}

