---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: SinLess Games Homepage
showStats: true

background: 
  image: https://img.freepik.com/free-photo/anime-moon-landscape_23-2151645903.jpg
  # blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

cardBlur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur

groupsInitiallyCollapsed: true

headerStyle: boxed

layout:
  Monitoring:
    icon: mdi-code-brackets
    style: row
    initiallyCollapsed: false
    columns: 4
    Pometheus:
      icon: prometheus.svg
      columns: 4
      style: row
      initiallyCollapsed: false

  Networking:
    initiallyCollapsed: false
    icon: mdi-network
  
  Cloudflare Tunnels:
    initiallyCollapsed: false
    icon: mdi-cloud
  
  Infrastructure:
    initiallyCollapsed: false
    icon: mdi-network
    columns: 4
  
  # Development:
  #   icon: fas fa-code

  # Security:
  #   icon: fas fa-shield-alt

  # Automation:
  #   icon: fas fa-robot

theme: dark
color: slate

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: [google, duckduckgo, brave]

hideVersion: true