---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- logo:
        icon: https://sinlessgamesllc.com/_next/image?url=%2Fimages%2F3.png&w=640&q=75

- resources:
        cpu: true
        memory: true
        disk: /

- unifi_console:
        url: {{HOMEPAGE_VAR_UNIFI_URL}}
        username: {{HOMEPAGE_VAR_UNIFI_USER}}
        password: {{ HOMEPAGE_VAR_UNIFI_PASSWORD}}

- datetime:
        text_size: xl
        format:
              timeStyle: short
              hourCycle: h23
