# Use compose up not stack deplopy
# There is a wierd bug where the service will not access the other services if you use stack deploy

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    ports:
      # This should expose on port 3000 to the external world
      - 3000:3000
    environment:
      - LOG_LEVEL=info
      # Cloudflared
      - HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID=${CLOUDFLARE_TUNNEL_ID}
      - HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      # Watchtower
      - HOMEPAGE_VAR_WATCHTOWER_API_TOKEN=${WATCHTOWER_API_TOKEN}
      # Unifi
      - HOMEPAGE_VAR_UNIFI_URL=${HOMEPAGE_VAR_UNIFI_URL}
      - HOMEPAGE_VAR_UNIFI_USER=${HOMEPAGE_VAR_UNIFI_USER}
      - HOMEPAGE_VAR_UNIFI_PASSWORD=${HOMEPAGE_VAR_UNIFI_PASSWORD}
      # Prometheus
      - HOMEPAGE_VAR_SWARM_PROMETHEUS_URL=${HOMEPAGE_VAR_SWARM_PROMETHEUS_URL}
      # Grafna
      - HOMEPAGE_VAR_GRAFANA_URL=${HOMEPAGE_VAR_GRAFANA_URL}
      - HOMEPAGE_VAR_GRAFANA_USER=${HOMEPAGE_VAR_GRAFANA_USER}
      - HOMEPAGE_VAR_GRAFANA_PASSWORD=${HOMEPAGE_VAR_GRAFANA_PASSWORD}
      # InfluxDB
      - HOMEPAGE_VAR_INFLUXDB_URL=${HOMEPAGE_VAR_INFLUXDB_URL}
      - HOMEPAGE_VAR_INFLUXDB_USER=${HOMEPAGE_VAR_INFLUXDB_USER}
      - HOMEPAGE_VAR_INFLUXDB_PASSWORD=${HOMEPAGE_VAR_INFLUXDB_PASSWORD}
      # Proxmox
      - HOMEPAGE_VAR_PROXMOX_URL=${HOMEPAGE_VAR_PROXMOX_URL}
      - HOMEPAGE_VAR_PROXMOX_USER=${HOMEPAGE_VAR_PROXMOX_USER}
      - HOMEPAGE_VAR_PROXMOX_PASSWORD=${HOMEPAGE_VAR_PROXMOX_PASSWORD}
    volumes:
      - ./config:/app/config
      - ./images:/app/images # for custom background images
      - ./icons:/app/icons # for custom icons
    networks:
      - frontend
      - backend
    
  