# Docker Compose configuration for the Homepage application
# -----------------------------------------------------------------------------
# NOTE:
# • Use "docker compose up" (not "docker stack deploy") to run this file.
#   There is a known bug in stack deploy that prevents inter-service communication.
#
# This configuration connects the Homepage container to two external networks:
#  - "frontend": intended for public traffic.
#  - "backend": for internal service communications.
#
# The container is configured to expose port 3000 to the external world.
# Environment variables are used to inject credentials and URLs for external services.
# -----------------------------------------------------------------------------
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    restart: always
    ports:
      # This should expose on port 3000 to the external world
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./config:/app/config
      - ./images:/app/images # for custom background images
      - ./icons:/app/icons # for custom icons
    networks:
      - frontend
      - backend
    
  