name: System-Critical-Services

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: overlay
    attachable: true
  
  frontend:
    driver: overlay
    attachable: true

services:
  traefik: 
    extends:
      file: ./traefik/docker-compose.yaml
      service: traefik

  cloudflared:
    extends:
      file: ./cloudflared/docker-compose.yaml
      service: cloudflared


  
  


