name: System-Critical-Services

volumes:
  postgres_data:
    driver: local
  
  redis_data:
    driver: local
  
  minio_data:
    driver: local

networks:
  backend:
    name: backend
    driver: overlay
    attachable: true
  
  frontend:
    name: frontend
    driver: overlay
    attachable: true
  
  unifi-network:
    name: unifi-network
    driver: bridge

include:
  - ./traefik/docker-compose.yaml
  - ./cloudflared/docker-compose.yaml
  - ./authentik/docker-compose.yaml
  - ./minio/docker-compose.yaml
  - ./watchtower/docker-compose.yaml
  # - ./sinlessgamesllc/docker-compose.yaml
  # - ./homepage/docker-compose.yaml

  

  


