name: System-Critical-Services

volumes:
  postgres_data:
    driver: local
  
  redis_data:
    driver: local
  
  minio_data:
    driver: local

networks:
  backend:
    name: backend
    driver: overlay
    attachable: true
  
  frontend:
    name: frontend
    driver: overlay
    attachable: true
  
  unifi-network:
    name: unifi-network
    driver: bridge

include:
  - ./traefik/docker-compose.yaml
  - ./cloudflared/docker-compose.yaml
  - ./authentik/docker-compose.yaml
  # - ./sinlessgamesllc/docker-compose.yaml
  # - ./homepage/docker-compose.yaml

services:
  # Distrubuted storage
  minio:
    image: minio/minio:latest
    container_name: minio
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      DOMAIN: ${DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend
      - frontend
    labels:
      # Traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.minio-http.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio-http.entrypoints=http"
      - "traefik.http.routers.minio-http.middlewares=redirect-to-https"
      - "traefik.http.routers.minio-http.service=minio"
      - "traefik.http.routers.minio-http.priority=1"

      - "traefik.http.routers.minio-https.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio-https.entrypoints=https"
      - "traefik.http.routers.minio-https.tls=true"
      - "traefik.http.routers.minio-https.service=minio"
      - "traefik.http.routers.minio-https.priority=1"
      - "traefik.http.routers.minio-https.tls.certresolver=cloudflare"

      - "traefik.http.services.minio.loadbalancer.server.port=9001"

      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    security_opt:
      - no-new-privileges=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend
    command: --interval 300 --cleanup

  


