networks:
  frontend:
    external: true
  backend:
    external: true

services:
  sinlessgames:
    image: sinless777/sinlessgames-ui:sha-c8ecadb
    container_name: sinlessgames
    restart: unless-stopped

    # Attach to both networks (frontend for Traefik ingress; backend if it talks to internal APIs)
    networks:
      - frontend
      - backend

    # Load runtime secrets/env (ROOT_DOMAIN, etc.)
    env_file:
      - ../../secrets/.env.runtime

    # If the app listens on a different port than 3000, update the healthcheck + traefik service port below.
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

    # No host ports; routed via Traefik
    labels:
      # ---- Traefik (external via Cloudflared) ----
      - "traefik.enable=true"
      - "traefik.http.routers.sinlessgames.rule=Host(`sinlessgamesllc.com`) || Host(`www.sinlessgamesllc.com`)"
      - "traefik.http.routers.sinlessgames.entrypoints=websecure"
      - "traefik.http.routers.sinlessgames.tls=true"
      - "traefik.http.services.sinlessgames.loadbalancer.server.port=3000"

      # ---- Homepage auto-discovery ----
      - "homepage.group=Applications"
      - "homepage.name=Sinless Games"
      - "homepage.icon=mdi-gamepad-variant"
      - "homepage.description=SinLess Games website"
      - "homepage.href=https://sinlessgamesllc.com"
      - "homepage.weight=5"
      - "homepage.widget.type=container"
      - "homepage.widget.container=sinlessgames"

      # ---- Watchtower ----
      - "com.centurylinklabs.watchtower.enable=true"

    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container=sinlessgames-frontend,service=applications,env=prod"
        loki-retries: "2"
        loki-max-backoff: "800ms"
        loki-timeout: "1s"
        keep-file: "true"
        mode: "non-blocking"
