networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  influxdb2-data:

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7.1-alpine
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Enable automatic updates with Watchtower
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=influxdb"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    networks:
      - frontend
      - backend
    ports:
      - "8086:8086" # Exposing the InfluxDB HTTP API
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUX_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PASSWORD}
      - INFLUXDB_ORG=${INFLUX_ORG}
      - INFLUXDB_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ./.data:/var/lib/influxdb2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
          