networks:
  backend:
    external: true
  frontend:
    external: true


services:
  sinlessgames:
    image: sinless777/sinlessgames-ui:1.0.89
    networks:
      - frontend
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sinlessgames-frontend"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M