global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Add a remote_write ONLY if you have a long-term store (e.g., VictoriaMetrics/Thanos)
# remote_write:
#   - url: "http://victoria-metrics:8428/api/v1/write"

scrape_configs:
  # Prometheus self-scrape
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Alertmanager (Docker service name)
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  # cAdvisor (container/node metrics)
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  # Loki metrics
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  # Watchtower metrics (HTTP API metrics enabled; path is /v1/metrics)
  - job_name: "watchtower"
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["watchtower:8080"]

  # Node Exporters on bare-metal/VMs
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "192.168.1.3:9100"
          - "192.168.1.8:9100"
          - "192.168.1.10:9100"
          - "192.168.1.11:9100"

  # Ceph exporters
  - job_name: "ceph"
    static_configs:
      - targets:
          - "192.168.1.8:9283"
          - "192.168.1.10:9283"
          - "192.168.1.11:9283"

  # Tempo (optional; if running)
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  # OpenTelemetry Collector (optional; if running the Prometheus exporter at 9464)
  - job_name: "otelcol"
    static_configs:
      - targets: ["otelcol:9464"]

  # Traefik (optional; enable metrics in Traefik first)
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:8080"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/rules/*.yaml"
