include:
  - ./ltm.yaml
  - ./oncall.yaml
  - ./prometheus.yaml
  - ./tools.yaml
  - ./influx-db.yaml

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    command: >-
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always 
    networks:
      - backend
    expose:
      - 3306
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: grafana
    deploy:
      resources:
        limits:
          memory: 1000m
          cpus: "0.5"
    healthcheck:
      test: "mysql -uroot -p$MYSQL_ROOT_PASSWORD grafana -e 'select 1'"
      timeout: 20s
      retries: 10

  grafana:
    image: "grafana/grafana:11.4.0"
    restart: always
    container_name: grafana
    depends_on:
      loki:
        condition: service_started
      mimir:
        condition: service_started
      engine:
        condition: service_started
      tempo:
        condition: service_started
      mysql:
        condition: service_healthy
      influxdb:
        condition: service_started
    networks:
      - backend
      - frontend
      - watchtower-network
    expose:
      - 3000
    environment:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: ${MYSQL_HOST:-mysql}
      GF_DATABASE_USER: ${MYSQL_USER:-root}
      GF_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      GF_FEATURE_TOGGLES_ENABLE: externalServiceAccounts
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-oncall-app
      GF_INSTALL_PLUGINS: grafana-oncall-app
      GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED: true
      GF_LOKI_URL: http://loki:3100
      GF_TEMPO_URL: http://tempo:3200
      GF_MIMIR_URL: http://mimir:9009
    volumes:
      - grafana-data:/etc/grafana
      - ./plugins/oncall.yaml:/etc/grafana/provisioning/plugins/oncall.yaml
      - ./configs/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    configs:
      - source: grafana.ini
        target: /etc/grafana/grafana.ini

configs:
  grafana.ini:
    content: |
      [feature_toggles]
      accessControlOnCall = false

networks:
  backend:
    external: true
  frontend:
    external: true
  watchtower-network:
    external: true

volumes:
  grafana-data:
    driver: local
  dbdata:
    driver: local
