services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./configs/loki.yaml:/etc/loki/local-config.yaml
    networks:
      - backend

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/local-config.yaml
    volumes:
      - ./configs/tempo.yaml:/etc/tempo/local-config.yaml
    networks:
      - backend

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009"
    command: -config.file=/etc/mimir/local-config.yaml
    volumes:
      - ./configs/mimir.yaml:/etc/mimir/local-config.yaml
    networks:
      - backend

  