services:
  ## Tools
  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    networks:
      - backend
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector:0.104.0
    container_name: otelcol
    # restart: unless-stopped
    networks:
      - backend
    ports:
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
      - 8888:8888 # monitoring
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - ./configs/otelcol.yaml:/etc/otelcol/config.yaml