networks:
  backend:
    external: true

services:
  ## Tools
  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    networks:
      - backend
    volumes:
      - /var/log:/var/log
      - ./configs/promtail.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector:0.104.0
    container_name: otelcol
    # restart: unless-stopped
    networks:
      - backend
    ports:
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
      - 8888:8888 # monitoring
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./configs/otelcol.yaml:/etc/otelcol/config.yaml
    
  goblog:
    image: mariomac/goblog:dev
    networks:
      - backend
    ports:
      # Exposes port 18843, forwarding it to container port 8443
      - "18443:8443"

  autoinstrumenter:
    image: grafana/beyla:latest
    pid: "service:goblog"
    privileged: true
    networks:
      - backend
    environment:
      BEYLA_TRACE_PRINTER: text
      BEYLA_OPEN_PORT: 8443