#Use compose up not stack deplopy
# There is a wierd bug where the service will not access the other services if you use stack deploy

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    container_name: homepage
    ports:
      # This should expose on port 3000 to the external world
      - 3000:3000
    environment:
      - LOG_LEVEL=info
      # Proxmox
      - HOMEPAGE_VAR_PROXMOX_USERNAME=${HOMEPAGE_VAR_PROXMOX_USERNAME}
      - HOMEPAGE_VAR_PROXMOX_PASSWORD=${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      - HOMEPAGE_VAR_PROXMOX_URL=${HOMEPAGE_VAR_PROXMOX_URL}
      # Pihole
      - HOMEPAGE_VAR_PIHOLE_KEY=${HOMEPAGE_VAR_PIHOLE_KEY}
      - HOMEPAGE_VAR_PIHOLE_URL=${HOMEPAGE_VAR_PIHOLE_URL}
      # Domains
      - DOMAIN=${DOMAIN}
      - HOMEPAGE_VAR_LOCAL_DOMAIN=${LOCAL_DOMAIN}
      # Cloudflared
      - HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID=${CLOUDFLARE_TUNNEL_ID}
      - HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      # Portainer
      - HOMEPAGE_VAR_PORTAINER_ACCESS_KEY=${HOMEPAGE_VAR_PORTAINER_ACCESS_KEY}
      - HOMEPAGE_VAR_PORTAINER_URL=${PORTAINER_URL}
      # Watchtower
      - HOMEPAGE_VAR_WATCHTOWER_API_TOKEN=${WATCHTOWER_API_TOKEN}
      # Unifi
      - HOMEPAGE_VAR_UNIFI_URL=${HOMEPAGE_VAR_UNIFI_URL}
      - HOMEPAGE_VAR_UNIFI_USER=${HOMEPAGE_VAR_UNIFI_USER}
      - HOMEPAGE_VAR_UNIFI_PASSWORD=${HOMEPAGE_VAR_UNIFI_PASSWORD}
      # Prometheus
      - HOMEPAGE_VAR_SWARM_PROMETHEUS_URL=${HOMEPAGE_VAR_SWARM_PROMETHEUS_URL}
      # Grafna
      - HOMEPAGE_VAR_GRAFANA_URL=${HOMEPAGE_VAR_GRAFANA_URL}
      - HOMEPAGE_VAR_GRAFANA_USER=${HOMEPAGE_VAR_GRAFANA_USER}
      - HOMEPAGE_VAR_GRAFANA_PASSWORD=${HOMEPAGE_VAR_GRAFANA_PASSWORD}
    volumes:
      - ./config:/app/config
      - ./images:/app/images # for custom background images
      - ./icons:/app/icons # for custom icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
