services:
  # Watchtower
  watchtower:
    image: containrrr/watchtower:latest                 # Use the latest Watchtower image
    container_name: watchtower                          # Name of the container
    restart: always                                     # Ensures the container restarts if it stops
    security_opt:
      - no-new-privileges=true                          # Enhances security by restricting privilege escalation
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock       # Grants Watchtower access to the Docker socket
    networks:
      - backend                                         # Connect to the backend network
      - frontend                                        # Connect to the frontend network
    command: --interval 300 --cleanup                   # Check for updates every 300 seconds (5 minutes) and clean up old images
