services:
  # Watchtower
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    security_opt:
      - no-new-privileges=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend
    command: --interval 300 --cleanup