services:
  mysql:
    image: mysql:8.0.32
    container_name: grafana-db
    command: >-
      --character-set-server=utf8mb4
    restart: always
    networks:
      - backend
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: grafana
    healthcheck:
      test: "mysql -uroot -p $MYSQL_ROOT_PASSWORD grafana -e 'select 1'"
      timeout: 40s
      retries: 10

  grafana:
    image: "grafana/grafana:11.4.0"
    container_name: grafana
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
      - frontend
    environment:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: ${MYSQL_HOST:-tasks.mysql}
      GF_DATABASE_USER: ${MYSQL_USER:-root}
      GF_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      GF_FEATURE_TOGGLES_ENABLE: externalServiceAccounts
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-oncall-app
      GF_INSTALL_PLUGINS: grafana-oncall-app
      GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED: 'true'
      GF_LOKI_URL: http://tasks.loki:3100
      GF_TEMPO_URL: http://tasks.tempo:3200
      GF_MIMIR_URL: http://tasks.mimir:9009
    volumes:
      - grafana-data:/etc/grafana
      - ./plugins/oncall.yaml:/etc/grafana/provisioning/plugins/oncall.yaml
      - ./configs/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"

networks:
  backend:
    external: true
  frontend:
    external: true

volumes:
  grafana-data:
    driver: local
  dbdata:
    driver: local
