networks:
  frontend:
    external: true
  backend:
    external: true

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - "9000:9000"
      - "40275:40275"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":40275"
    volumes:
      - ./.data:/data