services: 
  cloudflared:
    image: cloudflare/cloudflared:2024.2.1
    container_name: cloudflared
    restart: always
    networks:
      - backend
    volumes:
      - ./config:/etc/cloudflared:ro
    command: >
      tunnel run 92bf2c0e-68da-421d-8fbd-efcce8b60320
    environment:
      TZ: "${TZ:-UTC}"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
      resources:
        reservations:
          cpus: '0.10'
          memory: 128M
        limits:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


networks:
  backend:
    external: true
  
  frontend:
    external: true