networks:
  frontend:
    external: true
  backend:                                        # Backend network for inter-service communication
    external: true
  watchtower-network:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:2024.2.1
    restart: always
    networks:
      - frontend
      - backend
    command: >
      tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      TZ: "${TZ:-UTC}"
      CLOUDFLARE_TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    deploy:
      mode: global
      placement:
        constraints:
          - node.os == linux
      resources:
        reservations:
          cpus: '0.10'
          memory: 2048M
        limits:
          cpus: '0.25'
          memory: 2048M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s