# Docker Compose configuration for Watchtower
# -----------------------------------------------------------------------------
# Watchtower monitors your running containers and automatically updates them
# when new images are available. This configuration connects the Watchtower
# container to two external networks ("frontend" and "backend") so that it can
# interact with containers across your network.
#
# Environment variables are used to securely provide the API token used by
# Watchtower's HTTP API.
#
# -----------------------------------------------------------------------------

networks:
  backend:
    external: true
  frontend:
    external: true

services:
  watchtower:
    image: containrrr/watchtower:latest # Use the latest Watchtower image
    restart: always # Ensure container restarts if it stops
    environment:
      WATCHTOWER_API_TOKEN: ${WATCHTOWER_API_TOKEN}
    security_opt:
      - no-new-privileges=true # Restrict privilege escalation
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access Docker socket for updates
    networks:
      - frontend
      - backend
    command: >
      --interval 300 --cleanup --http-api-metrics true --http-api-token ${WATCHTOWER_API_TOKEN}
