################################################################################
# NETWORKS
################################################################################
networks:
  # 'backend' network is used for internal communication between services.
  backend:
    external: true  # Assumes an externally created network named 'backend' exists.
  # 'frontend' network is used to expose certain services to external clients.
  frontend:
    external: true  # Assumes an externally created network named 'frontend' exists.

services:
  ########################################
  # Pyroscope Service for Application Profiling
  ########################################
  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=Grafana-Pyroscope" # Change this to your the name of your container
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    restart: always  # Ensure container restarts if it stops unexpectedly.
    networks:
      - backend  # Use backend network for internal communication.
    ports:
      - "4040:4040"  # Expose port 4040 for Pyroscope UI.
    environment:
      # URL for the Pyroscope server (internal address).
      PYROSCOPE_SERVER: http://pyroscope:4040
      # Application name as recognized by Pyroscope.
      PYROSCOPE_APPLICATION_NAME: grafana
