networks:
  portainer-agent-network:                        # Network for Portainer agents
    name: portainer-agent-network
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"                           # Encrypts sensitive management traffic
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24                     # Subnet for Portainer agents
  backend:
    external: true
  frontend: 
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.24.1
    restart: always
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    environment:
      TZ: "${TZ:-UTC}"                            # Timezone configuration
    networks:
      - portainer-agent-network                   # Connect to dedicated Portainer agent network
      - frontend                                  # Accessible from the frontend network
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to Docker socket
      - ./.data/portainer:/data         # Persistent storage for Portainer data
      - /:/host                                  # Host access for system monitoring
    ports:
      - target: 9443
        published: 9443
        mode: host
    deploy:
      replicas: 1
      mode: replicated                                # Ensure one instance per node
      placement:
        constraints:
          - node.role == manager                  # Deploy only on manager nodes
      resources:
        reservations:
          cpus: "0.25"                            # Reserve 0.25 CPU
          memory: 256M                            # Reserve 256MB memory
        limits:
          cpus: "0.50"                            # Limit to 0.5 CPU
          memory: 512M                            # Limit to 512MB memory
      restart_policy:
        condition: on-failure                    # Restart on failure
        delay: 5s                                # Delay before restart
        max_attempts: 3                          # Retry up to 3 times
        window: 120s                             # Time window for retries

  agent:
    image: portainer/agent:2.24.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer-agent-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]