networks:
  portainer-agent-network:            # Network for Portainer agents
    driver: overlay
    attachable: true                  # Subnet for Portainer agents
  backend:
    external: true
  frontend: 
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.24.1
    restart: always
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    environment:
      TZ: America/Denver                          # Timezone configuration
    networks:
      - portainer-agent-network                   # Connect to dedicated Portainer agent network
      - frontend                                  # Accessible from the frontend network
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to Docker socket
      - ./.data/portainer:/data         # Persistent storage for Portainer data
      - /:/host                                  # Host access for system monitoring
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    deploy:
      replicas: 1
      mode: replicated                                # Ensure one instance per node
      placement:
        constraints:
          - node.role == manager                  # Deploy only on manager nodes
      restart_policy:
        condition: on-failure                    # Restart on failure
        delay: 5s                                # Delay before restart
        max_attempts: 3                          # Retry up to 3 times
        window: 120s                             # Time window for retries

  agent:
    image: portainer/agent:2.24.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-agent-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]