services:
  portainer:
    image: portainer/portainer-ce:2.24.1
    container_name: portainer
    restart: always
    environment:
      TZ: "${TZ:-UTC}"
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.data/portainer:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "0.25"
          memory: 256M
        limits:
          cpus: "0.50"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s