networks:
  backend:
    external: true

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Enable automatic updates with Watchtower
    restart: unless-stopped # Restart the container unless manually stopped
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=pdns-authoritative" # Change this to your the name of your container
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000                         # adjust to your user id
      - PGID=1000                         # adjust to your group id
      - TZ=Etc/UTC                        # set your time zone, e.g., America/New_York
      - SERVERPORT=51820                  # UDP port for WireGuard
      - PEERS=1                           # number of client configurations to generate
      - PEERDNS=192.168.1.1                # DNS server for peers (could be your router's IP)
      - INTERNAL_SUBNET=10.13.13.0/24       # VPN subnet (change as needed)
      - ALLOWEDIPS=192.168.1.0/24           # route the entire internal network to VPN clients
    volumes:
      - ./config:/config                  # persistent config directory
      - /lib/modules:/lib/modules        # required for loading kernel modules
    ports:
      - "51820:51820/udp"                 # expose WireGuard UDP port