networks:
  backend:
    external: true
  frontend:
    external: true
  
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    hostname: rancher
    restart: unless-stopped
    privileged: true
    networks:
      - frontend
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=rancher"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.rule=Host(`rancher.sinlessgamesllc.com`)"
      # Port 443
      - "traefik.http.services.rancher.loadbalancer.server.port=443"
      - "traefik.http.routers.rancher.tls=true"
      - "traefik.http.routers.rancher.entrypoints=websecure"
      - "traefik.http.routers.rancher.tls.certresolver=cloudflare"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data:/var/lib/rancher