services:
  # Distributed storage
  minio:
    image: minio/minio:latest
    container_name: minio
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      DOMAIN: ${DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend
      - frontend
    labels:
      # Traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.minio-http.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio-http.entrypoints=http"
      - "traefik.http.routers.minio-http.middlewares=redirect-to-https"
      - "traefik.http.routers.minio-http.service=minio"
      - "traefik.http.routers.minio-http.priority=1"
      
      - "traefik.http.routers.minio-https.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio-https.entrypoints=https"
      - "traefik.http.routers.minio-https.tls=true"
      - "traefik.http.routers.minio-https.service=minio"
      - "traefik.http.routers.minio-https.priority=1"
      - "traefik.http.routers.minio-https.tls.certresolver=cloudflare"

      - "traefik.http.services.minio.loadbalancer.server.port=9001"

      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"