name: PXE Boot Services

networks:
  frontend: # For outside calls coming into the stack
    external: true
  pxe-net:
    driver: bridge

services:
  tftp-server:
    image: pxe/tftp-server:0.4
    container_name: tftp-server
    networks:
      - pxe-net
    volumes:
      - ./tftp:/var/lib/tftpboot
    environment:
      - TFTP_ADDRESS=0.0.0.0
      - TFTP_PORT=69
    restart: always

  http-server:
    image: httpd:2.4.52-alpine
    container_name: http-server
    networks:
      - pxe-net
    volumes:
      - ./http:/usr/local/apache2/htdocs
    restart: always

  ipxe-server:
    image: ipxe/ipxe:stable
    container_name: ipxe-server
    networks:
      - pxe-net
    volumes:
      - ./ipxe:/var/www
    restart: always
    environment:
      - IPXE_URL=http://local.sinlessgamesllc.com/ipxe/boot.ipxe
    command: ["--interface", "eth0", "--dhcp-boot", "boot.ipxe"]

  dhcp-server:
    image: networkboot/dhcpd:latest
    container_name: dhcp-server
    networks:
      - pxe-net
    environment:
      - DHCPD_SUBNET=192.168.1.0
      - DHCPD_NETMASK=255.255.255.0
      - DHCPD_ROUTER=192.168.1.1
      - DHCPD_DNS=192.168.1.3
      - DHCPD_SERVER_IP=192.168.1.3
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
    restart: always

  cloud-init:
    image: cloud-init/cloud-init:latest
    container_name: cloud-init
    networks:
      - pxe-net
    volumes:
      - ./cloud-init:/etc/cloud
    restart: always
    command: ["cloud-init", "init"]

  # Virtual IP management
  keepalived:
    image: osixia/keepalived:latest
    container_name: keepalived
    networks:
      - pxe-net
    environment:
      - KEEPALIVED_VIRTUAL_IPS=192.168.1.13
      - KEEPALIVED_INTERFACE=eth0
      - KEEPALIVED_UNICAST_PEERS=192.168.1.3
      - KEEPALIVED_PRIORITY=100
      - KEEPALIVED_STATE=MASTER
    cap_add:
      - NET_ADMIN # Needed for network interface management
    restart: always

  stack-gateway:
    image: nginx:latest
    container_name: stack-gateway
    networks:
      - frontend
      - pxe-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Expose only NGINX HTTP port for external access via VIP
    restart: always
    environment:
      - VIRTUAL_HOST=local.sinlessgamesllc.com
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_PATH=/
      - VIRTUAL_PATH_REGEX=^/pxe(/|$)(.*)
      - LETSENCRYPT_HOST=local.sinlessgamesllc.com