# Define Docker networks to segment and manage communication between services.
networks:
  backend:
    name: backend

  frontend:
    # Frontend network for user-facing services
    name: frontend

services:
  setup:
    image: setup-image:latest # Replace with actual image name
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: setup-container
    restart: "no"
    networks:
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Grants access to Docker daemon
      - ./setup-scripts:/setup-scripts # Mounts local setup scripts
    environment:
      - ENV=production # Set deployment environment
    command: [ "/setup-scripts/setup.sh" ] # Executes the setup script
