# setup/docker-compose.yaml

# Define Docker networks to segment and manage communication between services.
networks:
  backend:
    name: backend
  frontend:
    # Frontend network for user-facing services
    name: frontend

services:
  setup:
    image: setup-image:latest  # Replace with your actual image name if needed.
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: setup-container
    restart: "no"  # This container is intended to run once during setup.
    networks:
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Grants access to Docker daemon.
    environment:
      - ENV=production  # Set the deployment environment.
    command: ["sudo", "-u", "deployer", "/setup/setup.sh"]  # Replace with actual setup commands.
