---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Personal-Github:
        - abbr: PGH
          href: https://github.com/Sinless777
    - SinLess-Games-Github:
        - abbr: SLGGH
          href: https://github.com/Sinless-Games
    - SinLess-Games-Enterprise-Github:
        - abbr: SLGEGH
          href: https://github.com/enterprises/sinlessgamesllc
    - GitLab:
        - abbr: GL
          href: https://gitlab.com/
    - Bitbucket:
        - abbr: BB
          href: https://bitbucket.org/

- Cloud:
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com/
    - Cloudflare-Dash:
        - abbr: CFD
          href: https://dash.cloudflare.com/
    - AWS:
        - abbr: AWS
          href: https://aws.amazon.com/
    - GCP:
        - abbr: GCP
          href: https://cloud.google.com/
    - Azure:
        - abbr: AZ
          href: https://azure.microsoft.com/
    - Linode:
        - abbr: LD
          href: https://www.linode.com/
    - DigitalOcean:
        - abbr: DO
          href: https://www.digitalocean.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - Twitter:
        - abbr: TW
          href: https://twitter.com/
    - Facebook:
        - abbr: FB
          href: https://facebook.com/
    - LinkedIn:
        - abbr: LI
          href: https://www.linkedin.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
    - YouTube-Music:
        - abbr: YTM
          href: https://music.youtube.com/
    - Netflix:
        - abbr: NF
          href: https://www.netflix.com/
    - Hulu:
        - abbr: HU
          href: https://www.hulu.com/
    - Spotify:
        - abbr: SP
          href: https://spotify.com/
    - Apple-Music:
        - abbr: AM
          href: https://music.apple.com/

- Anime:
    - H!anime:
        - abbr: HA
          href: https://hianime.to
    - Livechart:
        - abbr: LC
          href: https://www.livechart.me/

- Tools:
    - Docker:
        - abbr: DOCK
          href: https://www.docker.com/
    - Kubernetes:
        - abbr: K8S
          href: https://kubernetes.io/
    - Terraform:
        - abbr: TF
          href: https://www.terraform.io/
    - Ansible:
        - abbr: ANS
          href: https://www.ansible.com/
    - Helm:
        - abbr: HL
          href: https://helm.sh/

- News:
    - HackerNews:
        - abbr: HN
          href: https://news.ycombinator.com/
    - TechCrunch:
        - abbr: TC
          href: https://techcrunch.com/
    - Wired:
        - abbr: WD
          href: https://www.wired.com/
