---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Infrastructure:
    - pve-01:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        description: Proxmox Virtual Environment
        icon: proxmox.png
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_URL}}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-01
    - pve-02:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        description: Proxmox Virtual Environment
        icon: proxmox.png
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_URL}}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-02
    - pve-03:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        description: Proxmox Virtual Environment
        icon: proxmox.png
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_URL}}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-03
    - pve-pds-pc:
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        description: Proxmox Virtual Environment
        icon: proxmox.png
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_URL}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_URL}}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-pds-pc

- Networking:
    - pihole-lxc-01:
        href: '{{HOMEPAGE_VAR_PIHOLE_URL}}/admin'
        description: Pi-hole
        icon: pi-hole.svg
        siteMonitor: {{HOMEPAGE_VAR_PIHOLE_URL}}
        widget:
            type: pihole
            url: {{HOMEPAGE_VAR_PIHOLE_URL}}
            version: 5
            key: {{HOMEPAGE_VAR_PIHOLE_KEY}}

# - Development:

# - Automation:

# - Monitoring:

# - Security:
