datasources:
  # Prometheus data source configuration
  - name: Prometheus
    type: prometheus # Type of data source (Prometheus)
    access: proxy # Access method (proxy)
    url: http://prometheus:9090 # URL for accessing Prometheus
    basicAuth: false # Basic authentication is not enabled
    isDefault: false # Not the default data source
    version: 1 # Version of the data source
    uid: prometheus # Unique identifier for this data source

  # Loki data source configuration
  - name: Loki
    type: loki # Type of data source (Loki)
    access: proxy # Access method (proxy indicates Grafana will proxy the request)
    url: http://loki:3100 # URL for accessing Loki
    isDefault: false # Whether this is the default data source
    version: 1 # Version of the data source
    uid: loki # Unique identifier for this data source

  # Tempo data source configuration (used for tracing)
  - name: Tempo
    type: tempo # Type of data source (Tempo for tracing)
    access: proxy # Access method (proxy)
    orgId: 1 # Organization ID
    url: http://tempo:3200 # URL for accessing Tempo
    basicAuth: false # Basic authentication is not enabled
    isDefault: true # Tempo is the default data source
    version: 1 # Version of the data source
    editable: true # The data source is not editable
    apiVersion: 1 # API version of Tempo
    uid: tempo # Unique identifier for this data source

  # Pyroscope data source configuration (for profiling)
  - name: Pyroscope
    type: grafana-pyroscope-datasource # Type of data source (Pyroscope)
    access: proxy # Access method (proxy)
    url: http://pyroscope:4040 # URL for accessing Pyroscope
    basicAuth: false # Basic authentication is not enabled
    isDefault: false # Not the default data source
    editable: true # The data source is not editable
    version: 1 # Version of the data source
    uid: pyroscope # Unique identifier for this data source

  # OpenTelemetry Collector data source configuration (for tracing)
  - name: OpenTelemetry Collector
    type: jaeger # Type of data source (Jaeger, typically used for OpenTelemetry)
    access: proxy # Access method (proxy)
    url: http://opentelemetry-collector:14268 # URL for accessing the OpenTelemetry Collector
    basicAuth: false # Basic authentication is not enabled
    isDefault: false # Not the default data source
    editable: true # The data source is not editable
    version: 1 # Version of the data source
    uid: otel # Unique identifier for this data source
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"

  - name: InfluxDB
    type: influxdb # Type of data source (InfluxDB)
    access: proxy # Access method (proxy)
    url: http://influxdb:8086/metrics # URL for accessing InfluxDB
    basicAuth: false # Basic authentication is not enabled
    isDefault: false # Not the default data source
    version: 1 # Version of the data source
    uid: influxdb # Unique identifier for this data source
    jsonData:
      timeInterval: "5s"
    secureJsonData:
      password: ${INFLUX_PASSWORD}
      user: ${INFLUX_USER}
  
  - name: Github Data
    type: grafana-github-datasource
    editable: true
    jsonData:
      selectedAuthType: personal-access-token
    secureJsonData:
      accessToken: ${GITHUB_ACCESS_TOKEN}

  - name: 'Grafana Database'
    type: mysql
    url: mysql:3306
    user: root
    jsonData:
      database: grafana
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: ${MYSQL_ROOT_PASSWORD}
