receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['prometheus:9090']

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
