networks:
  backend:
    external: true
  frontend:
    external: true

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver

      # WireGuard port
      - SERVERPORT=51820

      # Number of peers (clients) you want to auto-generate
      - PEERS=1

      # Automatically use upstream DNS or specify your own
      - PEERDNS=auto

      # WireGuard virtual subnet (tunnel IPs for clients & server)
      - INTERNAL_SUBNET=10.8.0.0/24

      # List the subnets you want to route through the tunnel
      - ALLOWEDIPS=192.168.86.0/24,192.168.10.0/24

    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    networks:
      - backend
      - frontend