services:
  nginx:
    image: nginx:latest
    container_name: nginx_loadbalancer
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8006:8006"
    restart: unless-stopped
