################################################################################
# NETWORKS
################################################################################
networks:
  # 'backend' network is used for internal communication between services.
  backend:
    external: true  # Assumes an externally created network named 'backend' exists.
  # 'frontend' network is used to expose certain services to external clients.
  frontend:
    external: true  # Assumes an externally created network named 'frontend' exists.

services:
  ########################################
  # Tempo Service for Distributed Tracing
  ########################################
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=Grafana-Tempo" # Change this to your the name of your container
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    hostname: tempo
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/local-config.yaml
    volumes:
      - ./configs/tempo.yaml:/etc/tempo/local-config.yaml
    networks:
      - backend

  ########################################
  # OpenTelemetry Collector Service
  ########################################
  otelcol:
    image: otel/opentelemetry-collector:0.104.0
    restart: unless-stopped
    container_name: otelcol
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=otelcol"  # Ensure this matches your container name
        loki-retries: "3"  # Increased retries for reliability
        loki-max-backoff: "1s"  # Adjusted backoff time
        loki-timeout: "2s"  # Increased timeout to prevent log loss
        mode: "non-blocking"
    networks:
      - backend
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
      - 14268:14268  # Jaeger Thrift
      - 9464:9464  # Prometheus exporter
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./configs/otelcol.yaml:/etc/otelcol/config.yaml:ro  # Set as read-only to avoid accidental changes
