# -----------------------------------------------------------------------------
# Watchtower — Automated container update manager
# -----------------------------------------------------------------------------
# Watches all running containers (except itself) and updates them automatically
# if new images are available. Exposes a small HTTP API secured with a token,
# emits Prometheus metrics, and logs to Loki.
# -----------------------------------------------------------------------------

networks:
  frontend:
    external: true
  backend:
    external: true
  management:
    external: true

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped

    environment:
      # API token for HTTP access and metrics
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_API_TOKEN}
      WATCHTOWER_CLEANUP: "true"                  # remove old images after update
      WATCHTOWER_INCLUDE_STOPPED: "false"         # only running containers
      WATCHTOWER_POLL_INTERVAL: "300"             # check every 5 minutes
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_METRICS: "true"
      TZ: ${TZ:-America/Denver}

    command: >
      --interval 300
      --cleanup
      --http-api-update
      --http-api-metrics
      --http-api-token ${WATCHTOWER_API_TOKEN}
      --scope system-critical
      --label-enable

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    security_opt:
      - no-new-privileges:true

    networks:
      - frontend
      - backend
      - management

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/v1/info" , "--header=Authorization: Bearer ${WATCHTOWER_API_TOKEN}" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 15s

    labels:
      # ---- Homepage integration ----
      - "homepage.group=Management"
      - "homepage.name=Watchtower"
      - "homepage.icon=mdi-update"
      - "homepage.description=Auto-update running containers"
      - "homepage.href=http://watchtower.${LOCAL_DOMAIN}"
      - "homepage.widget.type=container"
      - "homepage.widget.container=watchtower"
      - "homepage.weight=15"

      # ---- Traefik (internal, optional if you want web access) ----
      - "traefik.enable=true"
      - "traefik.http.routers.watchtower.rule=Host(`watchtower.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.watchtower.entrypoints=websecure"
      - "traefik.http.routers.watchtower.tls=true"
      - "traefik.http.services.watchtower.loadbalancer.server.port=8080"

      # ---- Watchtower should not update itself ----
      - "com.centurylinklabs.watchtower.enable=false"

    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container=watchtower,service=management,env=prod"
        mode: "non-blocking"