# SOPS config for this repo
creation_rules:
  - path_regex: secrets/env\.sops\.yaml$
    encrypted_regex: '^(DATA)$'
    age:
      - "age1p3azc434jqnrx07aplxwtk3eefyd3f9sjxjs0vr7dxnjyljypcnsjrhjfr"
    pgp:
      # use the encryption subkey fingerprint, not the master key
      - "0BA826400BD02C59F43D912595DC365CBBAD99F5"
    path_suffix: .yaml
